---
tags:
- sinonimosDeTipos
- funcional
- tipos
- inmutabilidad
- aplicacionParcial
layout: input_right
editor: code
type: problem
extra_visible: false
language: 
teacher_info: 
manual_evaluation: false
